Issue#108
Universal-Variability-Language/uvl-lsp pull request #118
Opened 2023-11-09 12:17 UTC by ThiBruUU

Solving #108 by updating the UiAction:Set Event

2023-11-09 13:06 UTC, felixrieg requested changes

2023-11-09 13:28 UTC, ThiBruUU commented on uvls/src/webview.rs
> +#[derive(Debug)]
No, gets removed

2023-11-09 13:32 UTC, ThiBruUU commented on uvls/src/webview/frontend.rs
>                  val.set(to_number(&e.value));
yes, because the value in the configuration mask will not be updated and cant be changed.

2023-11-09 13:51 UTC, felixrieg commented on uvls/src/webview/frontend.rs
>                  val.set(to_number(&e.value));
Can't you just use
`value:"{init_val}",`

2023-11-10 09:42 UTC, ThiBruUU commented on uvls/src/webview/frontend.rs
>                  val.set(to_number(&e.value));
removed val

2023-11-10 10:02 UTC, felixrieg approved these changes
LGTM!

2023-12-05 16:32 UTC, merged